title:             Clean Blog
email:             clxkdk10@naver.com
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "/assets/vendor/startbootstrap-clean-blog"
url:               "http://clxkdk10.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
